services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: sentiblog-postgres
    environment:
      POSTGRES_USER: sentiblog
      POSTGRES_PASSWORD: sentiblog_dev_123
      POSTGRES_DB: sentiblog_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sentiblog"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: sentiblog-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API (Node.js)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: sentiblog-backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://sentiblog:sentiblog_dev_123@postgres:5432/sentiblog_dev
      REDIS_URL: redis://redis:6379
      JWT_SECRET: dev_jwt_secret_change_in_production
      PORT: 3001
      SENTIMENT_API_KEY: ${SENTIMENT_API_KEY}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3005}
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: npm run dev

  # Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: sentiblog-frontend
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXT_PUBLIC_WS_URL: ws://localhost:3001
    ports:
      - "3005:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    command: npm run dev

  # pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sentiblog-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sentiblog.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:

networks:
  default:
    name: sentiblog-network